table Store_dim
	lineageTag: 09f763ce-c8ab-4070-8464-80d7eb14f414

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: e1c91add-a9ce-45bc-93c1-38155a79f18b
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_location
		dataType: string
		lineageTag: 5c87becb-9407-4c46-997f-553ef5fc38d2
		summarizeBy: none
		sourceColumn: store_location

		annotation SummarizationSetBy = Automatic

	partition Store_dim = m
		mode: import
		source =
				let
				    Source = Koffee_Sales_source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"store_id", "store_location"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

